# Generated by Django 4.2.3 on 2024-11-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertising",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=350,
                        null=True,
                        verbose_name="نام تبلیغات",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ad/image",
                        verbose_name="تصویر تبلیغ",
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "تبلیغ",
                "verbose_name_plural": "تبلیغات",
                "ordering": ("-date_added",),
            },
        ),
    ]
