# Generated by Django 4.2.3 on 2024-11-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_advertising"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "podcast_name",
                    models.CharField(
                        max_length=550, null=True, verbose_name="نام پادکست"
                    ),
                ),
                (
                    "singer_name",
                    models.CharField(
                        max_length=550, null=True, verbose_name="نام گوینده"
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "در خواست پادکست",
                "verbose_name_plural": "در خواست های پادکست",
                "ordering": ("-date_added",),
            },
        ),
    ]
