# Generated by Django 4.2.3 on 2024-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_podcastrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="user/image/",
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
