# Generated by Django 4.2.3 on 2024-12-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_user_password_copy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=11),
        ),
    ]
