# Generated by Django 4.2.3 on 2025-01-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coin",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="سکه"
            ),
        ),
    ]
