# Generated by Django 4.2.3 on 2024-11-24 22:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=450, verbose_name="نام دسته بندی"),
                ),
                (
                    "discription",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته بندی ها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="آدرس آی پی")),
            ],
        ),
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=350, verbose_name="نام پادکست")),
                (
                    "english_title",
                    models.CharField(
                        max_length=350, null=True, verbose_name="نام اینگلیسی پادکست"
                    ),
                ),
                ("slug", models.SlugField(null=True)),
                (
                    "cover",
                    models.ImageField(
                        upload_to="music/cover/", verbose_name="کاور پادکست"
                    ),
                ),
                (
                    "podcast",
                    models.FileField(upload_to="music/musics/", verbose_name="پادکست"),
                ),
                (
                    "views",
                    models.IntegerField(default=0, verbose_name="تعداد بازدید ها"),
                ),
                (
                    "fit_by",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="ادیت شده توسط",
                    ),
                ),
                (
                    "favorite_count",
                    models.IntegerField(default=0, verbose_name="تعدا علاقه مندی ها"),
                ),
                (
                    "subscription",
                    models.BooleanField(
                        default=False,
                        null=True,
                        verbose_name="ایا این پادکست جزو اهنگ های اشتراکی است ؟",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="musics",
                        to="podcast.category",
                        verbose_name="دسته بندی",
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="musiclikes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="یوزر هایی که لایک کردند",
                    ),
                ),
            ],
            options={
                "verbose_name": "پادکست",
                "verbose_name_plural": "پادکست ها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Singer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="نام گوینده")),
                (
                    "image",
                    models.ImageField(
                        upload_to="music/singer/", verbose_name="عکس گوینده"
                    ),
                ),
                (
                    "discrip",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True,
                        help_text="اختیاری",
                        null=True,
                        verbose_name="توضیحات درباره ی گوینده",
                    ),
                ),
                (
                    "favorite_count",
                    models.IntegerField(default=0, verbose_name="تعدا علاقه مندی ها"),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="singerlikes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="یوزر هایی که لایک کردند",
                    ),
                ),
            ],
            options={
                "verbose_name": "گوینده  ",
                "verbose_name_plural": "گوینده ها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="SingerFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singer_favorites",
                        to="podcast.singer",
                        verbose_name="گوینده",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="singer_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقه مندی برای خواننده",
                "verbose_name_plural": "علاقه مندی ها برای خواننده",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="PodcastFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_favorites",
                        to="podcast.podcast",
                        verbose_name="پادکست",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="music_favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقه مندی برای پادسکت",
                "verbose_name_plural": "علاقه مندی ها برای پادکست",
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="podcast",
            name="singer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="podcast.singer",
                verbose_name="گوینده",
            ),
        ),
        migrations.CreateModel(
            name="PlayList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=350, null=True, verbose_name="نام پلی لیست"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="album/cover/", verbose_name="کاور پلی لیست"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "podcast",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="albums",
                        to="podcast.podcast",
                        verbose_name="پادکست ها",
                    ),
                ),
                (
                    "singer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="podcast.singer",
                        verbose_name="گوینده",
                    ),
                ),
            ],
            options={
                "verbose_name": "لیست پخش",
                "verbose_name_plural": "لیست ها پخش",
                "ordering": ("-created",),
            },
        ),
    ]
