# Generated by Django 4.2.3 on 2024-11-24 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="cover",
            field=models.ImageField(
                upload_to="playlists/cover/", verbose_name="کاور پلی لیست"
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="podcast",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="playlists",
                to="podcast.podcast",
                verbose_name="پادکست ها",
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="singer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="podcast.singer",
                verbose_name="گوینده",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="categories",
            field=models.ManyToManyField(
                related_name="podcasts", to="podcast.category", verbose_name="دسته بندی"
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="cover",
            field=models.ImageField(
                upload_to="podcast/cover/", verbose_name="کاور پادکست"
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="podcastlikes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="یوزر هایی که لایک کردند",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="podcast",
            field=models.FileField(upload_to="podcast/podcast/", verbose_name="پادکست"),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="singer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podcasts",
                to="podcast.singer",
                verbose_name="گوینده",
            ),
        ),
        migrations.AlterField(
            model_name="podcastfavorite",
            name="podcast",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podcast_favorites",
                to="podcast.podcast",
                verbose_name="پادکست",
            ),
        ),
        migrations.AlterField(
            model_name="podcastfavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="podcast_favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="singer",
            name="image",
            field=models.ImageField(
                upload_to="podcast/singer/", verbose_name="عکس گوینده"
            ),
        ),
    ]
