# Generated by Django 4.2.3 on 2024-11-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0002_alter_playlist_cover_alter_playlist_podcast_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
