# Generated by Django 4.2.3 on 2024-11-30 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("podcast", "0004_podcast_private_podcast_public_podcastsave"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="saves",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="podcastsaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="یوزر هایی که ذخیره کردند",
            ),
        ),
    ]
