# Generated by Django 4.2.3 on 2024-12-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0005_podcast_saves"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="podcast",
            field=models.ManyToManyField(
                blank=True,
                related_name="playlists",
                to="podcast.podcast",
                verbose_name="پادکست ها",
            ),
        ),
    ]
