# Generated by Django 4.2.3 on 2024-12-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Options",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        blank=True, max_length=650, null=True, verbose_name="گزینه"
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "گزینه",
                "verbose_name_plural": "گزینه ها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qs", models.TextField(blank=True, null=True, verbose_name="سوال")),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوال ها",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="MainQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تعداد درست"
                    ),
                ),
                (
                    "uncorrect_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تعداد نادرست"
                    ),
                ),
                (
                    "null_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="تعداد بدون جواب"
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "correct_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mainqs_correct",
                        to="qs_app.options",
                        verbose_name="گزینه درست",
                    ),
                ),
                (
                    "option1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mainqs1",
                        to="qs_app.options",
                        verbose_name="گزینه 1",
                    ),
                ),
                (
                    "option2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mainqs2",
                        to="qs_app.options",
                        verbose_name="گزینه 2",
                    ),
                ),
                (
                    "option3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mainqs3",
                        to="qs_app.options",
                        verbose_name="گزینه 3",
                    ),
                ),
                (
                    "option4",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mainqs4",
                        to="qs_app.options",
                        verbose_name="گزینه 4",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mainqs",
                        to="qs_app.question",
                        verbose_name="سوال",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال اصلی",
                "verbose_name_plural": "سوالات اصلی",
                "ordering": ("-created",),
            },
        ),
    ]
