# Generated by Django 4.2.3 on 2024-12-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("qs_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainquestion",
            name="user_correct_option_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="ایدی جواب که کاربر انتخاب کرده است",
            ),
        ),
        migrations.AlterField(
            model_name="mainquestion",
            name="correct_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correct_option",
                to="qs_app.options",
                verbose_name="جواب صیحیح",
            ),
        ),
    ]
