# Generated by Django 4.2.3 on 2024-12-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qs_app", "0002_mainquestion_user_correct_option_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainquestion",
            name="correct_count",
            field=models.IntegerField(default=0, verbose_name="تعداد درست"),
        ),
    ]
