# Generated by Django 4.2.3 on 2025-01-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0006_alter_playlist_podcast"),
        ("qs_app", "0003_alter_mainquestion_correct_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainquestion",
            name="podcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mainqs",
                to="podcast.podcast",
                verbose_name="پادکست",
            ),
        ),
    ]
