# Generated by Django 4.2.3 on 2025-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qs_app", "0004_mainquestion_podcast"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.TextField(
                        blank=True, null=True, verbose_name="متن راهنمایی"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("بالا", "بالا"),
                            ("متوسط", "متوسط"),
                            (" پایین", " پایین"),
                        ],
                        max_length=250,
                        null=True,
                        verbose_name="سطح راهنمایی",
                    ),
                ),
                (
                    "coin",
                    models.IntegerField(default=0, verbose_name="مقدار سکه مورد نیاز"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "راهنمایی",
                "verbose_name_plural": "راهنمایی ها",
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="mainquestion",
            name="hints",
            field=models.ManyToManyField(
                related_name="hint_podcast",
                to="qs_app.hint",
                verbose_name="راهنمایی ها",
            ),
        ),
    ]
